# config.yaml
rules_dir: "rules/"           # Directory containing OWASP rule files
graphs_dir: "../output"         # Directory containing AST/CFG/DFG files
output_path: "vulnerability_report.json"   # Output vulnerability report
language_dirs:
  java: rules/java
  c: rules/c
  cpp: rules/c